// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cart from "../Cart/Cart.mjs";
import * as React from "react";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as DatePicker from "../DatePicker/DatePicker.mjs";
import * as InventoryList from "../InventoryList/InventoryList.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReservationTypeSelection from "../ReservationTypeSelection/ReservationTypeSelection.mjs";

function str(prim) {
  return prim;
}

function addToCart(state, id) {
  return {
          cart: Belt_Array.concat(state.cart, [id]),
          selected_item: state.selected_item,
          items: state.items
        };
}

function removeFromCart(state, id) {
  return {
          cart: Js_array.filter((function (compareId) {
                  return compareId !== id;
                }), state.cart),
          selected_item: state.selected_item,
          items: state.items
        };
}

function Landing(props) {
  var dateB = props.dateB;
  var dateA = props.dateA;
  var now = new Date();
  var today = new Date(now.setHours(0.0, 0.0, 0.0, 0.0));
  var match = React.useState(function () {
        if (dateA !== undefined) {
          return new Date(dateA);
        } else {
          return today;
        }
      });
  var setOpenDate = match[1];
  var openDate = match[0];
  var match$1 = React.useState(function () {
        if (dateB !== undefined) {
          return new Date(dateB);
        } else {
          return openDate;
        }
      });
  var setCloseDate = match$1[1];
  var updateDate = function (openDate) {
    setOpenDate(openDate);
    setCloseDate(openDate);
  };
  var match$2 = React.useReducer((function (state, action) {
          console.log("calling reducer");
          console.log({
                state: state,
                action: action
              });
          var result;
          result = action.TAG === "AddToCart" ? addToCart(state, action.id) : removeFromCart(state, action.id);
          console.log({
                nextState: result
              });
          return result;
        }), {
        cart: [],
        selected_item: undefined,
        items: []
      });
  var state = match$2[0];
  var cartCount = state.cart.length;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("span", {
                                          children: JsxRuntime.jsx("i", {
                                                className: "light-icon-cloud"
                                              }),
                                          className: "m-2 align-middle text-3xl font-light"
                                        }),
                                    "Cloud Hardware Rental"
                                  ],
                                  className: "align-middle font-bold text-3xl m-2 text-zinc-700"
                                }),
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("span", {
                                          children: JsxRuntime.jsx("i", {
                                                className: "light-icon-calendar"
                                              }),
                                          className: "m-2 align-middle text-3xl font-light"
                                        }),
                                    "Select your reservation start date: "
                                  ],
                                  className: "align-middle text-gray-700 text-base m-2"
                                }),
                            JsxRuntime.jsx(DatePicker.make, {
                                  calendarClassName: "bg-white",
                                  className: "m-2 ml-14 block",
                                  isOpen: false,
                                  minDate: today,
                                  onChange: updateDate,
                                  selected: openDate
                                }),
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("span", {
                                          children: JsxRuntime.jsx("i", {
                                                className: "light-icon-file-invoice"
                                              }),
                                          className: "m-2 align-middle text-3xl font-light"
                                        }),
                                    "Select your reservation type: ",
                                    JsxRuntime.jsx(ReservationTypeSelection.make, {})
                                  ],
                                  className: "align-middle text-gray-700 text-base m-2"
                                }),
                            JsxRuntime.jsx(Cart.StateContext.Provider.make, {
                                  children: JsxRuntime.jsxs(Cart.DispatchContext.Provider.make, {
                                        children: [
                                          JsxRuntime.jsx(InventoryList.make, {
                                                openDate: openDate,
                                                closeDate: match$1[0],
                                                activeId: props.activeId
                                              }),
                                          JsxRuntime.jsx(Cart.make, {
                                                count: cartCount
                                              })
                                        ],
                                        value: match$2[1]
                                      }),
                                  value: state
                                }),
                            JsxRuntime.jsx("div", {
                                  children: JsxRuntime.jsx("button", {
                                        children: "Book Reservation",
                                        className: "mx-auto mt-4 bg-slate-500 hover:bg-slate-700 text-white py-2 px-4 rounded-sm"
                                      }),
                                  className: "w-full"
                                })
                          ],
                          className: "bg-zinc-100 rounded-sm px-4 py-4"
                        }),
                    className: "w-full rounded-sm shadow-lg p-4"
                  }),
              className: "justify-center flex items-center"
            });
}

var make = Landing;

export {
  str ,
  addToCart ,
  removeFromCart ,
  make ,
}
/* Cart Not a pure module */
