// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as React from "react";

async function $$fetch$1() {
  var response = await fetch("https://62210a40afd560ea69a5c07b.mockapi.io/mock", {
        method: "GET"
      });
  return JSON.parse(await response.text());
}

var empty = {
  inventory: []
};

var context = React.createContext(empty);

var provider = context.Provider;

function ExecutorHook$SSR$Provider(props) {
  return React.createElement(provider, {
              value: props.value,
              children: props.children
            });
}

var domExecutorConfig = ((typeof window !== 'undefined' ? window.__EXECUTOR_CONFIG__ ?? null : null));

var initialExecutorConfig = (domExecutorConfig == null) ? empty : domExecutorConfig;

var executorConfig = Tilia.tilia({
      config: Tilia.source(initialExecutorConfig, (async function (_prev, set) {
              var config = await $$fetch$1();
              return set(config);
            }))
    });

function useExecutor() {
  return executorConfig.config;
}

var ExecutorConfig = {
  $$fetch: $$fetch$1
};

var SSR_Provider = {
  make: ExecutorHook$SSR$Provider
};

var SSR = {
  empty: empty,
  context: context,
  Provider: SSR_Provider
};

export {
  ExecutorConfig ,
  SSR ,
  useExecutor ,
}
/* context Not a pure module */
