// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.res.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.res.mjs";

var InventoryItem = {};

var ExecutorConfig = {};

async function fetchExecutorConfig() {
  var response = await fetch("https://62210a40afd560ea69a5c07b.mockapi.io/mock", {
        method: "GET"
      });
  return JSON.parse(await response.text());
}

var empty = {
  inventory: []
};

var executorConfig = Tilia.source((async function (set) {
        return set(await fetchExecutorConfig());
      }), empty);

function useExecutor() {
  TiliaReact.useTilia();
  return executorConfig;
}

export {
  InventoryItem ,
  ExecutorConfig ,
  useExecutor ,
}
/* executorConfig Not a pure module */
