// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";

var InventoryItem = {};

var ExecutorConfig = {};

async function fetchExecutorConfig() {
  var response = await fetch("https://62210a40afd560ea69a5c07b.mockapi.io/mock", {
        method: "GET"
      });
  return JSON.parse(await response.text());
}

var empty = {
  inventory: []
};

var executorConfig = Tilia.tilia({
      config: Tilia.source(empty, (async function (_prev, set) {
              var config = await fetchExecutorConfig();
              return set(config);
            }))
    });

function useExecutor() {
  TiliaReact.useTilia();
  console.log(executorConfig);
  return executorConfig.config;
}

export {
  InventoryItem ,
  ExecutorConfig ,
  useExecutor ,
}
/* executorConfig Not a pure module */
