// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

function Loading(props) {
  return JsxRuntime.jsx("h1", {
              children: "Loading..."
            });
}

var make = Loading;

export {
  str ,
  make ,
}
/* react/jsx-runtime Not a pure module */
