// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function formatCurrency(amount, locale, currency) {
  var locale_ = Belt_Option.getWithDefault(locale, "en-US");
  var currency_ = Belt_Option.getWithDefault(currency, "USD");
  var formatter = Intl.NumberFormat(locale_, {
        style: "currency",
        currency: currency_
      });
  return formatter.format(amount);
}

export {
  formatCurrency ,
}
/* No side effect */
