// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as NumberFormatter from "./NumberFormatter.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Pricing(props) {
  var format_price = function (p) {
    return NumberFormatter.formatCurrency(p / 100, undefined, undefined);
  };
  var map_period = function (p) {
    return JsxRuntime.jsxs(React.Fragment, {
                children: [
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx("p", {
                              children: p.label,
                              className: "text-left text-sm"
                            }),
                        className: "border-1 border-black/30 p-1"
                      }),
                  JsxRuntime.jsx("div", {
                        children: JsxRuntime.jsx("p", {
                              children: format_price(p.price),
                              className: "text-left text-sm"
                            }),
                        className: "border-1 border-black/30 p-1"
                      })
                ]
              }, String(p.id));
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("p", {
                            children: "Unit",
                            className: "font-bold text-left"
                          }),
                      className: "border-1 border-slate-200/50 bg-black/30 text-white p-1"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("p", {
                            children: "Price",
                            className: "font-bold text-left"
                          }),
                      className: "border-1 border-slate-200/50 bg-black/30 text-white p-1"
                    }),
                Belt_Array.map(props.period_list, map_period)
              ],
              className: "rounded-lg border-1 border-slate-200/50 grid grid-cols-2 bg-white"
            });
}

var make = Pricing;

export {
  make ,
}
/* react Not a pure module */
