// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import ReactDatePickerShimMjs from "../shims/reactDatePickerShim.mjs";

import "react-datepicker/dist/react-datepicker.css"
;

var make = ReactDatePickerShimMjs;

var Raw = {
  make: make
};

function DatePicker(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsClient = match[1];
  React.useEffect((function () {
          setIsClient(function (param) {
                return true;
              });
        }), []);
  if (match[0]) {
    return JsxRuntime.jsx(make, {
                calendarClassName: props.calendarClassName,
                className: props.className,
                isOpen: props.isOpen,
                minDate: props.minDate,
                onChange: props.onChange,
                selected: props.selected
              });
  } else {
    return null;
  }
}

var make$1 = DatePicker;

export {
  Raw ,
  make$1 as make,
}
/*  Not a pure module */
