// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Card(props) {
  var className = props.className;
  console.log("classes:" + Core__Option.getOr(className, ""));
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: Cx.cx([
                    "m-1 p-1 bg-slate-100/70 border-hairline border-b-2 border-slate-200 shadow-sm shadow-slate-200/70 rounded-lg",
                    Core__Option.getOr(className, "")
                  ])
            });
}

var make = Card;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
