// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Container(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "m-1.5 p-1 bg-slate-100 border-hairline border-b-2 border-slate-200 shadow-sm shadow-slate-200/70"
            });
}

var make = Container;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
