// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LucideReact from "lucide-react";
import * as JsxRuntime from "react/jsx-runtime";

var Calendar = {
  make: LucideReact.Calendar
};

var Clock = {
  make: LucideReact.Clock
};

var MonitorCloud = {
  make: LucideReact.MonitorCloud
};

var Cloud = {
  make: LucideReact.Cloud
};

var SearchIcon = {
  make: LucideReact.SearchIcon
};

function Icon$IconButton(props) {
  return JsxRuntime.jsx("button", {
              children: JsxRuntime.jsx(props.icon.make, {
                    size: 16,
                    color: "white"
                  })
            });
}

var IconButton = {
  make: Icon$IconButton
};

JsxRuntime.jsx(Icon$IconButton, {
      icon: Cloud
    });

export {
  Calendar ,
  Clock ,
  MonitorCloud ,
  Cloud ,
  SearchIcon ,
  IconButton ,
}
/* Calendar Not a pure module */
