// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

function ErrorView(props) {
  return JsxRuntime.jsx("h1", {
    children: "Error"
  });
}

let make = ErrorView;

export {
  str,
  make,
}
/* react/jsx-runtime Not a pure module */
