// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

function itemCount(state) {
  return state.length;
}

var context = React.createContext(function (_action) {
      
    });

var provider = context.Provider;

function Cart$DispatchContext$Provider(props) {
  return React.createElement(provider, {
              value: props.value,
              children: props.children
            });
}

var Provider = {
  provider: provider,
  make: Cart$DispatchContext$Provider
};

var DispatchContext = {
  context: context,
  Provider: Provider
};

var state_cart = [];

var state_items = [];

var state = {
  cart: state_cart,
  selected_item: undefined,
  items: state_items
};

var context$1 = React.createContext(state);

var provider$1 = context$1.Provider;

function Cart$StateContext$Provider(props) {
  return React.createElement(provider$1, {
              value: props.value,
              children: props.children
            });
}

var Provider$1 = {
  provider: provider$1,
  make: Cart$StateContext$Provider
};

var StateContext = {
  state: state,
  context: context$1,
  Provider: Provider$1
};

function Cart(props) {
  var cartState = React.useContext(context$1);
  React.useContext(context);
  console.log({
        CartState: cartState
      });
  return JsxRuntime.jsxs("h1", {
              children: [
                JsxRuntime.jsx("span", {
                      children: JsxRuntime.jsx("i", {
                            className: "light-icon-shopping-cart"
                          }),
                      className: "m-2 align-middle text-3xl font-light"
                    }),
                "Selected equipment (",
                String(props.count),
                ")"
              ],
              className: "block font-bold align-middle text-gray-700 text-base m-2 text-3xl"
            });
}

var make = Cart;

export {
  str ,
  itemCount ,
  DispatchContext ,
  StateContext ,
  make ,
}
/* context Not a pure module */
