// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Landing from "../Landing/Landing.res.mjs";
import * as ErrorView from "../ErrorView/ErrorView.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function getActiveId(url) {
  var match = url.path;
  if (!match) {
    return ;
  }
  if (match.hd !== "item") {
    return ;
  }
  var match$1 = match.tl;
  if (match$1) {
    return match$1.hd;
  }
  
}

function App(props) {
  var initialUrl = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useState(function () {
        return initialUrl;
      });
  var setUrl = match[1];
  var url = match[0];
  var match$1 = React.useState(function () {
        return getActiveId(url);
      });
  var setActiveId = match$1[1];
  var activeId = match$1[0];
  React.useEffect((function () {
          var watcherID = RescriptReactRouter.watchUrl(function (newUrl) {
                console.log("URL changed to:", newUrl.path);
                setUrl(function (param) {
                      return newUrl;
                    });
                setActiveId(function (param) {
                      return getActiveId(newUrl);
                    });
              });
          return (function () {
                    RescriptReactRouter.unwatchUrl(watcherID);
                  });
        }), []);
  var match$2 = url.path;
  if (match$2 && match$2.hd !== "item") {
    return JsxRuntime.jsx(ErrorView.make, {});
  } else {
    return JsxRuntime.jsx(Landing.make, {
                activeId: activeId
              });
  }
}

var make = App;

export {
  getActiveId ,
  make ,
}
/* react Not a pure module */
