// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Landing from "../Landing/Landing.mjs";
import * as Premise from "../State/Premise.mjs";
import * as ErrorView from "../ErrorView/ErrorView.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function getActiveId(url) {
  var match = url.path;
  if (!match) {
    return ;
  }
  if (match.hd !== "item") {
    return ;
  }
  var match$1 = match.tl;
  if (match$1) {
    return match$1.hd;
  }
  
}

function App(props) {
  var initialExecutorConfig = props.initialExecutorConfig;
  var initialUrl = RescriptReactRouter.useUrl(props.serverUrl, undefined);
  var match = React.useState(function () {
        return initialUrl;
      });
  var setUrl = match[1];
  React.useEffect((function () {
          var watcherID = RescriptReactRouter.watchUrl(function (newUrl) {
                console.log("URL changed to:", newUrl.path);
                setUrl(function (param) {
                      return newUrl;
                    });
              });
          return (function () {
                    RescriptReactRouter.unwatchUrl(watcherID);
                  });
        }), []);
  var executorConfigValue = initialExecutorConfig !== undefined ? initialExecutorConfig : Premise.SSR.empty;
  var match$1 = match[0].path;
  var tmp;
  tmp = match$1 && match$1.hd !== "item" ? JsxRuntime.jsx(ErrorView.make, {}) : JsxRuntime.jsx(Landing.make, {});
  return JsxRuntime.jsx(Premise.SSR.Provider.make, {
              value: executorConfigValue,
              children: tmp
            });
}

var make = App;

export {
  getActiveId ,
  make ,
}
/* react Not a pure module */
