// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pricing from "../Pricing/Pricing.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function str(prim) {
  return prim;
}

var make = TiliaReact.leaf(function (props) {
      var item = props.item;
      var id = item.id;
      var matches = [];
      var matchCount = matches.length;
      if (matchCount > 0) {
        String(matches.length);
      }
      String(item.quantity - matchCount | 0);
      return JsxRuntime.jsx("a", {
                  children: JsxRuntime.jsxs("button", {
                        children: [
                          JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsx("img", {
                                      className: "p-[1.5] w-40 h-40",
                                      style: {
                                        width: "100%"
                                      },
                                      src: "https://placeholdr.ai/1ca27004-f6f9-413a-8dbf-6c088feabead/256/256"
                                    }),
                                className: "rounded-sm shadow-sm m-0 p-0"
                              }),
                          JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsx("h2", {
                                      children: item.name,
                                      className: "tracking-wider text-xs"
                                    }),
                                className: "flex flex-row justify-between w-full bg-gray-300 text-white shadow-sm"
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx("p", {
                                        children: item.description,
                                        className: "text-xs text-left m-2"
                                      }),
                                  JsxRuntime.jsx(Pricing.make, {
                                        period_list: item.period_list
                                      })
                                ],
                                className: "flex flex-col flex-grow flex-1 w-full bg-white/40 rounded-sm m-[1.5] justify-between items-end"
                              })
                        ],
                        className: "relative m-[1.5] flex flex-1 flex-col flex-grow max-w-40"
                      }),
                  className: "flex flex-1 flex-col flex-grow border-2",
                  id: "item-" + String(id),
                  href: "/item/" + String(id),
                  onClick: (function (e) {
                      e.preventDefault();
                      RescriptReactRouter.replace("/item/" + String(id));
                    })
                });
    });

export {
  str ,
  make ,
}
/* make Not a pure module */
