// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pricing from "../Pricing/Pricing.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.mjs";

function str(prim) {
  return prim;
}

function InventoryItem(props) {
  var item = props.item;
  var id = item.id;
  var matches = [];
  var matchCount = matches.length;
  var quantity = matchCount > 0 ? String(matches.length) : "0";
  var available = String(item.quantity - matchCount | 0);
  return JsxRuntime.jsx("a", {
              children: JsxRuntime.jsxs("button", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("img", {
                                  className: "p-[1.5] w-40 h-40",
                                  style: {
                                    width: "100%"
                                  },
                                  src: "https://placeholdr.ai/1ca27004-f6f9-413a-8dbf-6c088feabead/256/256"
                                }),
                            className: "rounded-sm border-2 shadow-sm m-0 p-0"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("span", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "light-icon-shopping-cart text-xl"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: quantity,
                                            className: "text-[0.5rem]",
                                            title: "Quantity in cart"
                                          })
                                    ],
                                    className: "drop-shadow-sm"
                                  }),
                              JsxRuntime.jsxs("span", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "light-icon-checks text-xl"
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: available,
                                            className: "text-[0.5rem]",
                                            title: "Quantity available"
                                          })
                                    ],
                                    className: "drop-shadow-sm"
                                  })
                            ],
                            className: "flex flex-row justify-between w-full bg-gray-300 text-white shadow-sm"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h2", {
                                    children: item.name,
                                    className: "text-xs"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: item.description,
                                    className: "text-xs m-2"
                                  }),
                              JsxRuntime.jsx(Pricing.make, {
                                    period_list: item.period
                                  })
                            ],
                            className: "flex flex-col text-align-center w-full bg-white/40 rounded-sm m-[1.5] justify-self-end"
                          })
                    ],
                    className: "relative m-[1.5] flex flex-col  max-w-40"
                  }),
              className: "block",
              id: "item-" + String(id),
              href: "/item/" + String(id),
              onClick: (function (e) {
                  e.preventDefault();
                  RescriptReactRouter.replace("/item/" + String(id));
                })
            });
}

var make = InventoryItem;

export {
  str ,
  make ,
}
/* Pricing Not a pure module */
