// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function computeState(config) {
  var seen_units = new Set();
  return Belt_Array.flatMap(config.inventory, (function (inv) {
                    return inv.period_list.map(function (pl) {
                                if (seen_units.has(pl.unit)) {
                                  return ;
                                } else {
                                  seen_units.add(pl.unit);
                                  return Caml_option.some(pl);
                                }
                              });
                  })).filter(function (pl) {
                return pl !== undefined;
              }).map(function (pl) {
              return pl;
            });
}

export {
  computeState ,
}
/* No side effect */
