// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";

var match = Tilia.signal("Hourly");

var defaultState = "Hourly";

var state = match[0];

var set = match[1];

export {
  defaultState ,
  state ,
  set ,
}
/* match Not a pure module */
