// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as React from "react";

async function $$fetch$1(premiseId) {
  var response = await fetch("http://localhost:5173/api/config/" + premiseId, {
        method: "GET"
      });
  return JSON.parse(await response.text());
}

var empty = {
  inventory: []
};

var context = React.createContext(empty);

var provider = context.Provider;

function Premise$SSR$Provider(props) {
  return React.createElement(provider, {
              value: props.value,
              children: props.children
            });
}

var domExecutorConfig = ((typeof window !== 'undefined' ? window.__EXECUTOR_CONFIG__ ?? null : null));

var initialExecutorConfig = (domExecutorConfig == null) ? empty : domExecutorConfig;

var state = Tilia.tilia({
      config: Tilia.source(initialExecutorConfig, (async function (_prev, set) {
              var config = await $$fetch$1("a55351b1-1b78-4b6c-bd13-6859dc9ad410");
              return set(config);
            }))
    });

var Config = {
  $$fetch: $$fetch$1
};

var SSR_Provider = {
  make: Premise$SSR$Provider
};

var SSR = {
  empty: empty,
  context: context,
  Provider: SSR_Provider
};

export {
  Config ,
  SSR ,
  state ,
}
/* context Not a pure module */
