// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Premise from "./Premise.mjs";

var match = Tilia.signal("Hourly");

var signal = match[0];

var Period_set = match[1];

var Period = {
  defaultState: "Hourly",
  signal: signal,
  set: Period_set
};

var main_store = Tilia.tilia({
      config: Premise.state,
      period: Tilia.lift(signal)
    });

export {
  Period ,
  main_store ,
}
/* match Not a pure module */
