// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Premise from "./Premise.mjs";
import * as PeriodList from "./PeriodList.mjs";

var match = Tilia.signal("hour");

var signal = match[0];

var Unit_set = match[1];

var Unit = {
  defaultState: "hour",
  signal: signal,
  set: Unit_set
};

var main_store = Tilia.carve(function (param) {
      return {
              config: Premise.state,
              period_list: param.derived(PeriodList.deriveState),
              unit: Tilia.lift(signal)
            };
    });

export {
  Unit ,
  main_store ,
}
/* match Not a pure module */
