// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Premise from "./Premise.mjs";

var match = Tilia.signal("Hour");

var signal = match[0];

var Unit_set = match[1];

var Unit = {
  defaultState: "Hour",
  signal: signal,
  set: Unit_set
};

var main_store = Tilia.tilia({
      config: Premise.state,
      unit: Tilia.lift(signal)
    });

export {
  Unit ,
  main_store ,
}
/* match Not a pure module */
