// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "../State/State.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

var make = TiliaReact.leaf(function (props) {
      return JsxRuntime.jsx("div", {
                  children: State.period_list.map(function (period) {
                        return JsxRuntime.jsxs("label", {
                                    children: [
                                      JsxRuntime.jsx("input", {
                                            className: "m-1",
                                            id: "type_" + period.unit,
                                            autoComplete: "off",
                                            checked: State.main_store.unit === period.unit,
                                            name: "type",
                                            type: "radio",
                                            value: "hour",
                                            onChange: (function (e) {
                                                var inputEl = e.currentTarget;
                                                if (inputEl.checked !== true) {
                                                  return ;
                                                }
                                                var match = period.unit;
                                                switch (match) {
                                                  case "day" :
                                                      return State.Unit.set("day");
                                                  case "hour" :
                                                      return State.Unit.set("hour");
                                                  case "minute" :
                                                      return State.Unit.set("minute");
                                                  case "month" :
                                                      return State.Unit.set("month");
                                                  case "second" :
                                                      return State.Unit.set("second");
                                                  case "week" :
                                                      return State.Unit.set("week");
                                                  case "year" :
                                                      return State.Unit.set("year");
                                                  default:
                                                    return State.Unit.set(State.Unit.defaultState);
                                                }
                                              })
                                          }),
                                      JsxRuntime.jsx("span", {
                                            children: period.label,
                                            className: "p-1 pl-0"
                                          })
                                    ],
                                    className: "block",
                                    htmlFor: "type_" + period.unit
                                  }, period.unit);
                      }),
                  className: "my-auto"
                });
    });

export {
  str ,
  make ,
}
/* make Not a pure module */
