// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "../State/State.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

var make = TiliaReact.leaf(function (props) {
      return JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("label", {
                          children: [
                            JsxRuntime.jsx("input", {
                                  className: "m-1",
                                  id: "type_hourly",
                                  autoComplete: "off",
                                  checked: State.main_store.period === "Hourly",
                                  name: "type",
                                  type: "radio",
                                  value: "hour",
                                  onChange: (function (e) {
                                      var inputEl = e.currentTarget;
                                      if (inputEl.checked === true) {
                                        return State.Period.set("Hourly");
                                      }
                                      
                                    })
                                }),
                            JsxRuntime.jsx("span", {
                                  children: " Per Hour",
                                  className: "p-1 pl-0"
                                })
                          ],
                          htmlFor: "type_hourly"
                        }),
                    JsxRuntime.jsxs("label", {
                          children: [
                            JsxRuntime.jsx("input", {
                                  className: "m-1",
                                  id: "type_daily",
                                  autoComplete: "off",
                                  checked: State.main_store.period === "Daily",
                                  name: "type",
                                  type: "radio",
                                  value: "date",
                                  onChange: (function (e) {
                                      var inputEl = e.currentTarget;
                                      if (inputEl.checked === true) {
                                        return State.Period.set("Daily");
                                      }
                                      
                                    })
                                }),
                            JsxRuntime.jsx("span", {
                                  children: " Per Day",
                                  className: "p-1 pl-0"
                                })
                          ],
                          htmlFor: "type_daily"
                        })
                  ],
                  className: "my-auto"
                });
    });

export {
  str ,
  make ,
}
/* make Not a pure module */
