// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Ui/Card.mjs";
import * as Icon from "../Ui/Icon.mjs";
import * as State from "../State/State.mjs";
import * as React from "react";
import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as InventoryItem from "../InventoryItem/InventoryItem.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function str(prim) {
  return prim;
}

var cmp = Caml_obj.compare;

var IntCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

var make = TiliaReact.leaf(function (props) {
      var activeId = props.activeId;
      var closeDate = props.closeDate;
      var openDate = props.openDate;
      var config = State.main_store.config;
      var unit = State.main_store.unit;
      var items = config.inventory;
      var filterType = "all";
      var now = new Date();
      var today = new Date(now.setHours(0.0, 0.0, 0.0, 0.0));
      var openDate$1 = openDate !== undefined ? Caml_option.valFromOption(openDate) : today;
      var closeDate$1 = closeDate !== undefined ? Caml_option.valFromOption(closeDate) : today;
      React.useEffect((function () {
              console.log("Open Date:");
              console.log(openDate$1);
              console.log("Close Date:");
              console.log(closeDate$1);
              return (function () {
                        
                      });
            }), [
            openDate$1,
            closeDate$1
          ]);
      var heading = unit !== "Hour" && Caml_obj.notequal(openDate$1, closeDate$1) ? "Showing " + filterType + " equipment available from " + openDate$1.toLocaleDateString() + " to " + closeDate$1.toLocaleDateString() : "Showing " + filterType + " equipment available " + (
          openDate$1.getTime() === today.getTime() ? "today" : openDate$1.toLocaleDateString()
        );
      return JsxRuntime.jsxs(Card.make, {
                  children: [
                    JsxRuntime.jsxs("h1", {
                          children: [
                            JsxRuntime.jsx(Icon.SearchIcon.make, {
                                  className: "inline"
                                }),
                            JsxRuntime.jsx("span", {
                                  children: heading,
                                  className: "align-middle"
                                })
                          ],
                          className: "block align-middle text-lg content-center"
                        }),
                    JsxRuntime.jsx(Card.make, {
                          children: Js_array.map((function (item) {
                                  return JsxRuntime.jsx(InventoryItem.make, {
                                              item: item,
                                              _active: Caml_obj.equal(activeId, String(item.id))
                                            }, String(item.id));
                                }), items),
                          className: "border-none shadow-none shadow-transparent m-0 p-0 place-content-start grid lg:grid-cols-8 grid-cols-4 gap-4"
                        })
                  ],
                  className: "m-0 p-0 bg-white/30 border-2 border-b-4 border-r-4 border-gray-200/60"
                });
    });

export {
  str ,
  IntCmp ,
  make ,
}
/* IntCmp Not a pure module */
