// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App/App.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import "./tailwind.css"
;

import "react-datepicker/dist/react-datepicker.css"
;

var rootElement = document.querySelector("#root");

if (rootElement == null) {
  console.log("No root element found");
} else {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(App.make, {}));
}

var rootElement$1 = (rootElement == null) ? undefined : Caml_option.some(rootElement);

export {
  rootElement$1 as rootElement,
}
/*  Not a pure module */
